/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Obfuscation */

#ifndef _Included_Obfuscation
#define _Included_Obfuscation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Obfuscation
 * Method:    cjniobfuscation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Obfuscation_cjniobfuscation
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
